# Generated by Django 5.2.4 on 2025-07-30 05:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='adds/%Y/%m', verbose_name='file')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'add',
                'verbose_name_plural': 'adds',
                'db_table': 'add',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'news category',
                'verbose_name_plural': 'news categories',
                'db_table': 'news category',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'news tag',
                'verbose_name_plural': 'news tags',
                'db_table': 'news tag',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('type', models.CharField(choices=[('supertop', 'supertop'), ('top', 'supertop'), ('editor choice', 'editor choice'), ('latest', 'latest'), ('actual', 'actual'), ('video', 'video'), ('article', 'article'), ('interview', 'interview'), ('announcement', 'announcement'), ('motivation', 'motivation'), ('photo', 'photo')], max_length=256, verbose_name='type')),
                ('cover', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='cover')),
                ('video', models.URLField(verbose_name='video')),
                ('file', models.FileField(blank=True, null=True, upload_to='news/files/%Y/%m/%d', verbose_name='file')),
                ('time_to_read', models.PositiveIntegerField(default=0, verbose_name='time to read')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='published_at')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='common.newscategory', verbose_name='category')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='news', to='common.newstag', verbose_name='tags')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='common.region', verbose_name='region')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'news',
            },
        ),
    ]
