# Generated by Django 5.2.4 on 2025-08-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='Teams/%Y/%m', verbose_name='image')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('position', models.CharField(max_length=256, verbose_name='position')),
            ],
            options={
                'verbose_name': 'teams',
                'verbose_name_plural': 'teams',
                'db_table': 'teams',
            },
        ),
    ]
